version: '3'
services:
  client:
    image: teregudi/multi-client
    ports:
      - "3000:3000"
  server:
    image: teregudi/multi-server
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
  worker:
    image: teregudi/multi-worker
  nginx:
    image: teregudi/multi-nginx
    ports:
      - "80:80"
    depends_on:
      server:
        condition: service_healthy
      client:
        condition: service_started
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres_password
  redis:
    image: redis:latest