version: '3'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.dev
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  jenkins_home: