version: '3'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: teregudi/multi-client
    ports:
      - "3000:3000"
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: teregudi/multi-server
    ports:
      - "5000:5000"
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    image: teregudi/multi-worker
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: teregudi/multi-nginx
    ports:
      - "80:80"
    depends_on:
      - client
      - server
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres_password
  redis:
    image: redis:latest